name: R CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup R environment
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("testthat", "knitr", "rmarkdown"), repos = "https://cran.rstudio.com/")'

    - name: Check package
      run: |
        R CMD build .
        R CMD check *tar.gz --no-manual

    - name: Test package
      run: |
        Rscript -e 'testthat::test_dir("tests/testthat")'




