name: R-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: Rscript -e 'if (!requireNamespace("devtools")) install.packages("devtools"); devtools::install_deps(dependencies = TRUE)'

    - name: Run tests
      run: Rscript -e 'devtools::test()'




