name: R-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: Rscript -e 'install.packages(c("testthat", "roxygen2", "knitr"))'

    - name: Build package
      run: R CMD build .

    - name: Install package
      run: R CMD INSTALL JackiePackage_*.tar.gz

    - name: Run tests
      run: Rscript -e 'testthat::test_dir("tests/testthat")'



